### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by grchannels** [DevLARLEY/mpdl#1]
Where and what is CDM? Can you make a simple video of the "Usage" steps? 
Thank you!

**Comment by DevLARLEY** [comment]
A CDM or Content Decryption Module consists of 2 files which are needed for emulating a device that retrieves the decryption keys for the video.
You can _generate_ one using [Android Studio](https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio).

**Comment by pawelglucklich** [comment]
ill hijack it... i used Android studio to create those files and renamed them as pointed out. Proceed to add both, click apply, but than if i click browser it prompts me again to choose cdm.

**Comment by DevLARLEY** [comment]
Did you place them in "data/pywidevine/L3/cdm/devices/android_generic/"?
If not, please make sure that you've renamed them correctly.

**Comment by pawelglucklich** [comment]
I did
https://i.imgur.com/IBcGgm9.png

________________________________

**Comment by DevLARLEY** [comment]
Remove the file extensions ;)

**Comment by pawelglucklich** [comment]
i just have set up as default to show all file extensions. does it matter?
________________________________

**Comment by pawelglucklich** [comment]
Ok i got it finally to work. 
Unfortunately I now run into this error.
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 271: character maps to undefined

is there a way to change charset decodes for opened files somewhere in config?

**Comment by DevLARLEY** [comment]
When and where are you getting that error?

**Comment by pawelglucklich** [comment]
Im step 11 in "Usage" documentation on github. Error is shown to me in
console in VSC where I run it. 
https://i.imgur.com/aEtgdtT.png

im trying to use it on this site btw: https://35mm.online/

**Comment by DevLARLEY** [comment]
Opening a manifest file really shouldn't cause decoding errors. I guess you could post the manifest URL here?

MPDL is a literal piece of junk software i programmed. Here are some of the things i don't hate about it:
- Doesn't request manifest; it instead saves AS A FILE and opens it again
- Writes the headers TO A .PY FILE IN PLAIN TEXT
- Saves all headers in a HUGE dictionary 
- GUI shifts around when using on anything other than Windows 11/10
- Uses Selenium which is a pain to use
- Formats headers py using .replace()

This thing will get archived once i get to release the predecessor to this program (hopefully soon) because every time somebody opens an issue i have to try to temporarily fix some bug that was meant to happen since the release.

**Comment by pawelglucklich** [comment]
not sure what you mean...

this is my license https://i.imgur.com/ZTzD0NE.png
and those are my [MPD urls](https://i.imgur.com/GGgS4ZT.png)... not sure which one i should pick but if i pick anything else but the ones with "audio&bitrate" at the end it shows ["no found PSSH error](https://i.imgur.com/rAdp5Xy.png). Anything else will crash with wrong charset error.

**Comment by DevLARLEY** [comment]
It should always be the first url that seems like it could be a manifest (contains '.ism', '.mpd', 'Manifest'). The program crashes because the other urls you selected are video segments which cannot be decoded into plaintext.

**Comment by pawelglucklich** [comment]
Manifest.ism all of them contain. I cant seem to find a single one with .mpd though.

**Comment by pawelglucklich** [comment]
I have like 3 major groups of urls.

One that ends with  audio&bitrate
one that ends with video&bitrate
and odd ones.

all of oddones report no PSSH.
audio and video ones crash on charset - none of them seem to contain any .mpd. also they differentiate by start=xxxxxxx value.

**Comment by pawelglucklich** [comment]
Is it possible that it cannot find PSSH in a file that should contain it (one of those odd ones)? since other files crash on charset in getPSSH function too?

**Comment by DevLARLEY** [comment]
My new program already has support for it and the manifest file regex seems to be 'https://[-\w]+\.dcs\.redcdn\.pl/.*/Manifest\.ism\?indexMode' so i guess it should work with the first URL? Please post it here so i can take a look at it manually.

**Comment by pawelglucklich** [comment]
you want me to post first URL from MPD list?

**Comment by pawelglucklich** [comment]
https://i.imgur.com/8ypjwk3.png
https://i.imgur.com/Zyo4uOE.png

**Comment by DevLARLEY** [comment]
> you want me to post first URL from MPD list?

yes

**Comment by pawelglucklich** [comment]
is there any way to copy it?

**Comment by pawelglucklich** [comment]
https://r.dcs.redcdn.pl/dash/o2/wfdif/cps/prod/vod/599a237d-da3a-47f1-9252-bf9d1febf7eb/MOVIE/LIBCODER_SMOOTH_1080_WFDIF/Manifset.ism?indexMode

welp thats first one on the list manually copied... so might have a typos.

**Comment by DevLARLEY** [comment]
404 Not Found. Why not copy it from the network tab? (F12)

**Comment by pawelglucklich** [comment]
didnt know i could
https://r.dcs.redcdn.pl/dash/o2/wfdif/cps/prod/vod/599a237d-da3a-47f1-9252-bf9d1febf7eb/MOVIE/LIBCODER_SMOOTH_1080_WFDIF/Manifest.ism?indexMode
so the one i send you before has status 302
this one is status 200 and its right after one before
https://n-6-5.dcs.redcdn.pl/dash/o2/wfdif/cps/prod/vod/599a237d-da3a-47f1-9252-bf9d1febf7eb/MOVIE/LIBCODER_SMOOTH_1080_WFDIF/Manifest.ism?indexMode

**Comment by DevLARLEY** [comment]
Yep, it's using an initialisation file with the pssh inside. The MPD is saying that your init file should be a segment but not have a start= parameter. Download it and use my initext on the local file to get the pssh. Then enter everything manually into Advanced Mode or whatever it's called

**Comment by pawelglucklich** [comment]
not sure what and how should i download
one of the mp4 segments?
any one or specific one?

**Comment by DevLARLEY** [comment]
![image](https://github.com/DevLARLEY/mpdl/assets/121249322/915b29c2-42ca-4d5d-9773-afacf3e97f6a)
to download the file, double click this URL in the network tab (F12)
then, run [initext](https://github.com/DevLARLEY/initext/releases/download/v2.1/initext_x64.exe) using 'initext_64 FILEPATH'

**Comment by pawelglucklich** [comment]
it started and keep progressing for good 10-20min after which it throws up this https://i.imgur.com/m6Gi5t1.png
no console errors

**Comment by DevLARLEY** [comment]
have you selected your executables in the settings menu?

**Comment by pawelglucklich** [comment]
You mean ffmpeg and mp4decrypt?
I only found ffpmeg to install and add as global variables. All i can find for mp4decrypt is bento4<https://github.com/axiomatic-systems/Bento4> package for c++. Should i install it? Alternatively where can i find those executables?
[https://opengraph.githubassets.com/ff884d7fc7bfdf3bf1cdc539ad30cb9f7fc4ecc26a2ec3613943602c42c95d31/axiomatic-systems/Bento4]<https://github.com/axiomatic-systems/Bento4>
GitHub - axiomatic-systems/Bento4: Full-featured MP4 format, MPEG DASH, HLS, CMAF SDK and tools<https://github.com/axiomatic-systems/Bento4>
Full-featured MP4 format, MPEG DASH, HLS, CMAF SDK and tools - axiomatic-systems/Bento4
github.com

________________________________

**Comment by DevLARLEY** [comment]
ffmpeg: [https://www.gyan.dev/ffmpeg/builds/](https://www.gyan.dev/ffmpeg/builds/)
mp4decrypt: [https://www.bento4.com/downloads/](https://www.bento4.com/downloads/)

**Comment by pawelglucklich** [comment]
Sorry... I forgot what to put in License server field. Been a week since i sat to it. BTW thank you very much for your time so far. Especially since im chipping at your time on other projects with this old one.
________________________________

**Comment by pawelglucklich** [comment]
OK. It actually worked this time, Start to finish. Thank you for your very patience help.

Solution:
Put everything manually in advanced mode:
- MPD URL
- extracted PSSH
- License URL
- ffmpeg filepath
- mp4decrypt filepath

PS also might need to update whatever packages tell you to upgrade in console (i had to update couple), sometimes to specific version (not necessarily to newest ones).
