### ISSUE TITLE
no PSSH found in URL

### ISSUE THREAD

**Issue by Psychonaut74** [DevLARLEY/mpdl#2]
hi, I followed all the instructions, but when I click on Download I get the error message "no PSSH found in URL". Any suggestions?

**Comment by DevLARLEY** [comment]
that just means that the program couldn't find any pssh in the mpd file linked to the url. not an error with the program (probably). you mind posting the link?

**Comment by Psychonaut74** [comment]
![Screenshot at 09-33-00](https://github.com/DevLARLEY/mpdl/assets/95238087/3099a142-732a-4ec4-b9c1-57a21d8263a2)

**Comment by Psychonaut74** [comment]
HI. I'm also trying to use MultiMPDTool
![Screenshot at 13-26-04](https://github.com/DevLARLEY/mpdl/assets/95238087/032f7158-ac6c-4180-b305-2e162ff9c184)
 but I'm getting this error. Where could the problem be? Thank you.

**Comment by DevLARLEY** [comment]
For MultiMPDTool:
Did you follow the [usage instructions](https://github.com/DevLARLEY/MultiMPDTool#usage)?

For mpdl:
If you want me to troubleshoot the "error" you'll have to send me the full link or, if you for some reason don't want to send the link, you can attach the mpd file to your message. (There is no reason to blur the link. It's just a link to a streaming file on a hosting server.)

**Comment by Psychonaut74** [comment]
For MultiMPDTool, I followed all the instructions. The path for 'WKS-KEYS\pywidevine\L3\cdm\devices\android_generic' must be in MultiMPDTool root directory right?
This is the mpd: https://videos.mubicdn.net/preview/1f1a59edd6f4979fcfbbc75fef46ab14/65b17324/74b5217a/315/384/mubi-films/960/shadows-in-par_fin_zxx_1920x1080_30000_mezz42440/652ca281d3/playlist.60fbff2af5.ism/default/ver1.AVC1.2160p.ex-eac3.mpd
Thanks

**Comment by DevLARLEY** [comment]
The [multimpdtool.py](https://github.com/DevLARLEY/MultiMPDTool/blob/main/multimpdtool.py) must be in the WKS-KEYS directory and there must be a working CDM in WKS-KEYS\pywidevine\L3\cdm\devices\android_generic

**Comment by Psychonaut74** [comment]
I moved the file multimpdtool.py to the WKS-KEYS folder and yes, there are working CDM in that location ('device_client_id_blob' and 'device_private_key right'? without extension). But I still get the ModuleNotFoundError: No module named 'pywidevine.L3'

**Comment by DevLARLEY** [comment]
just tested it and it works
this is how it's supposed to look
![image](https://github.com/DevLARLEY/mpdl/assets/121249322/076f79d9-d54f-4b27-92c1-3484973c9bce)
inside the [WKS-KEYS](https://github.com/SASUKE-DUCK/WKS-KEY/releases)
![image](https://github.com/DevLARLEY/mpdl/assets/121249322/5e16b178-57e3-4015-8bac-94fd65fa968f)

and yes the cdm files don't have an extension
![image](https://github.com/DevLARLEY/mpdl/assets/121249322/4e4f87a2-3f6b-4e89-8749-4b805f9dab82)

**Comment by Psychonaut74** [comment]
Now everything seems to be in its place, but I keep getting this error.
What is the 'venv' folder? 
It is possible to have your working  folder without the 'device_client_id_blob and device_private_key' files?
I also have ffmpeg and mp4decrypt in the WKS-KEYS foldere.
![Screenshot at 16-20-35](https://github.com/DevLARLEY/mpdl/assets/95238087/dd2f17d5-4901-4c0f-a0e8-5969f7eec687)
![Screenshot at 16-31-58](https://github.com/DevLARLEY/mpdl/assets/95238087/53df57c1-7772-47c0-a8ae-7140e73075de)

Thanks

**Comment by DevLARLEY** [comment]
looks fine...

is there an L3 folder inside the pywidevine folder?
if not, try using the WKS-KEYS version linked in my post above.

what command are you running?
what's your python version?

a venv is a virtual environment, basically a copied version of your systemwide python installation so the modules you install don't contaminate your main python installation. it's not required if you just want to use the program.

**Comment by Psychonaut74** [comment]
Hi, I'm using Python 3.12.1 and I'm running the command 'python multimpdtool.py' (not python3 because I get the error Python non found.).
Still getting the No module error. :/

**Comment by DevLARLEY** [comment]
are you sure that there is an L3 folder inside 'pywidevine'?
i'll also try python 3.12.1 even though there is no way that that's the problem.
so running python --version returns 3.12.1?

try this version if WKS-KEYS i used:
[link](https://github.com/SASUKE-DUCK/WKS-KEY/releases)
please note that the files in the rar file have to be inside a folder with the multimpdtool.py

**Comment by Psychonaut74** [comment]
Hi. Yes, the python --version returns 3.12.1
And the is no a L3.py file inside the pywidevine, just the L3 Folder.

**Comment by DevLARLEY** [comment]
the only thing that could work is trying to use [this](https://github.com/SASUKE-DUCK/WKS-KEY/releases/download/WKS-KEY-V3/wks-keys.rar) WKS-KEYS version.
if that doesn't work, i can't help you :/

**Comment by Psychonaut74** [comment]
Hi! Thank you for your help and patience! :)
I did a new installation from scratch but now the error I have is: 'unable to parse license - check protobufs
[EROR] Unable to extract key(s).'
Any suggestions? Thanks again

**Comment by DevLARLEY** [comment]
the "unable to parse license - check protobufs" is an error that is coming from WKS-KEYS.
it can have pretty much any cause but my guess is that you didn't supply any headers.
it can also be caused by a wrong License URL (which i don't think is the case here)

**Comment by Psychonaut74** [comment]
Ok. 
How do I give information to the headers? 
What I did is copy the drm_playlist.3d###.dash (inside the Network tab) as a cURL, convert them to Python (on https://curlconverter.com/) and paste them into the "headers.py" file inside the WKS-KEYS folder.
I keep getting the same error:
'unable to parse license - check protobufs
[EROR] Unable to extract key(s).'
What I'm missing? :(
Thank you mate!

**Comment by DevLARLEY** [comment]
what is "drm_playlist.3d###.dash" in your case? it's not an mpd file and not a license url.
copying as cURL is correct but you need to copy the request headers from the license url.
multimpdtool should ask you to input headers. just paste the converted headers from curlconverter.com into the cmd, press enter, type ";;" and press enter again to stop pasting.

**Comment by Psychonaut74** [comment]
Ok.. but how to copy the request headers from the license url as curl? :(

**Comment by DevLARLEY** [comment]
to find the license url search for something like 'lic', 'loken' or 'widevine' but the first one shoudl be enough.
right click and choose (in Firefox) Copy Value -> Copy as cURL (POSIX) and paste that into curlconverter.com

**Comment by Psychonaut74** [comment]
In the Network tab, if I filter 'lic', 'loken' or 'widevine' nothing is shown... :(
How the headers should look like? I have something like:
   'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0',
    'Accept': '*/*',
    'Accept-Language': 'en',
    # 'Accept-Encoding': 'gzip, deflate, br',
    'Referer': '',
    'client': 'web',
    'client-accept-video-codecs': 'vp9,h264',
    'client-accept-audio-codecs': 'aac',
    'x-real-ip': '',
    'x-forwarded-for': '',
    'x-forwarded-proto': 'https',
    'anonymous_user_id': '',
    'client-country': 'IT',
    'authorization': '',
    # Already added when you pass json=
    # 'content-type': 'application/json',
    'Origin': 'https://mubi.com',
    'Connection': 'keep-alive',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    # Requests doesn't support trailers
    # 'TE': 'trailers',

But it doesnt work.
What about key(s) instead of License URL? Thoose key should start with ey?

**Comment by DevLARLEY** [comment]
to get the keys you need a pssh and a license url.
i added this option so that if you already had the keys you wouldn't need to request them again.

i forgot to tell you but licenses always use post requests. so enter 'method:POST' in your network search box.

if you still can't find it you could maybe post the link of the video here.

**Comment by Psychonaut74** [comment]
Hi! I found the 'lic' filtering after broweser refresh.
I copied as cURL (POSIX) in Firefox, paste it into curconverter.
What I have to paste now into MultiMPDTool when it ask for:
'Input headers (y/n)?' y
----
headers = {
.....
}
---

How it is formatted? 
Thanks again

**Comment by Psychonaut74** [comment]
![Scsh01](https://github.com/DevLARLEY/mpdl/assets/95238087/6794b083-4583-4756-930a-b22b8aee5fc5)
![Scsh02](https://github.com/DevLARLEY/mpdl/assets/95238087/71b00e08-51d8-433e-985f-bbf1b085a497)

**Comment by DevLARLEY** [comment]
where did you get the pssh from that you entered manually?

**Comment by Psychonaut74** [comment]
I followed Point 3 on this: https://lxlit.dev/posts/cdm-tools/obtaining-pssh/
Using EME Logger options

**Comment by DevLARLEY** [comment]
seems like your downloading from mubi, which is a non-free service so it may require an L1 CDM or some time limited token. i can't help you with that.

**Comment by Psychonaut74** [comment]
Ok, thank you anyway! I really apprecieted. :)
I have my Mubi account active, anyway.
