### ISSUE TITLE
Unable to Parse License

### ISSUE THREAD

**Issue by mjfarooq** [DevLARLEY/mpdl#5]
Hi, I'm getting an error in getting license from server. It seems that the server is expecting a json, which the script is not supplying. Here is what I get (printing the challenge and server response):

Worker(
f16d7cd6-6227-401f-a0f3-a50a6df21a18.mpd,
AAAAgHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAGASEFBu0SMDAtWmlix2wzMT/hISENKMKmqzTWKcxYxKZxVvzEsSEHnxeKni/Tvd2Fexv1qZLl8SEKo+k93YkkkD7qVJjfjRttUSED4g6Kx7EMphcg2SblNBqGhI49yVmwY=,
https://mw.hivesys.net/widevine_proxy,
f16d7cd6-6227-401f-a0f3-a50a6df21a18)
License Request Data (Challenge): CAESkQ8K8g0IARKaCwrdAwgCEhArCXww7zJhcTYCs33DTvI7GO6V6q4GIo4CMIIBCgKCAQEApvZJ6myKXAfmW8eQhAGvcVZnhDnU0ZxNeN0aXmvDu5IYVr7GmRuuAB7M6Pie8mQS/pHz+lOWMrJA6ILWdsl9Aj5Y5rd8JbN2gn8OgFqYaGx3j4OnOIrDfAvFbwjiYdZ4TaIaxsl/a+HRPOUO5FzKK1lrcIK1ezFqNrLG0L7ddvU9SezU1/sTFH5KUSdBWw9ojBEzeBhMjYSGfGw9E7rSSnDgL8dOBk16PzAQiTNPUG6TZdYFUlTs+8jZJvt/fsBOd8jjXsLlggr30Sq2JRvQtagAV2UFOmpN2csrPHTIq0SsjqRXnET4RAYywq0OvMmF7a8QsDkNkjHB+p+CnFw92wIDAQABKPAiSAFSqgEIARAAGoEBBEmjbZn0SqYn5BgA2FxnjZRQHIn8kRDwXgwq3kXSFSrs1U/dSRPY8idHiTsqfTD0aKwGixVt7v1zNh1Byl//xSgcAFrFkIrFl9fhuoeNnZEoqpG0HYuutSiFGgR0rM1GO7FJwwa0ekF80IS8l7pEClYvuyDvSf0GxbBJ31p3lkCvIiDcxpdYpb8kei6+kdc/4ei3FH0F7JxTxqCXoBTrL5Dz/BKAAlH0aNBP43l5Hwm+fm4vphwvd6cfnFPhSj7h9ljsosFL4pI9o7VX4wXg/OQlHTM76kTnwglPfjc3cCjOrzn4YO3IyAkCMjGBlEAZSZDMVB31SVXZHiTTAY25pWTWTGmJv5vfvO7FEGUd8qYLG39OaBk0PwH7zi3PyqaD6eVsGGcPF916pct9YlgeMS2b0R7hqUJbWZGWi1T9uGo/UZiax7/IgYNVjJhaJrZSdSBWn7LMx0EmNV+kiUD77GDTWM/DN/ABygN/2WftzoM8V85NBGV7/lNeAhLGa8Prr0mUFCF+2vSxb/lc2cbnqqXAsWr0nawM4gNncydUobhHA5ZlV6MatAUKrgIIARIQaePomLssP7ijsygdhPiMFBiO1b6RBSKOAjCCAQoCggEBANj26bWJ8FEg6aQ+0NlOof4JlQFtvR4rQKfc0cV/wwVQPM8TP56Yr85O5v+E3EIkJqj/+k/kvy1E1Q8UOuu8IEyjtGf6JRv6YD/bJeInqK+pw30K72Lmo5TXKCif1JZlGy6MUUHyfFWt5jkvN6rTbzfOfUKDWy1xfi04dPu60/MUb9F4MVC3Q78YuXNXAHR3WyfdIow7hcuOFl2dyu0X2OWOmDvGMwiWdYlSrEOjtNCRPK0mZSXSRwztud0Et6sB0kUZpdzqhJjh43L8gYOW4sJBHcpkRCzL+Yt5XWCBDjgwWvtc4z6t37j/fXir915BuMeqNYW5WvyIhopur5HrdKECAwEAASjwIhKAAyKLYzDrP5CzVu+/EZK2J722lyCg7a4C3lm+/QINe+sWXCdJuj6pHvVG7YiVlZVJs3ldhIgPBzAHMeNjys2vd+Cxe1Im3Ljbl2M1C0Xn4naOsCF/dDabsQjlqiFkakPYTRyv51WP2jzHS4lHY1ZHwVWhVBJdmlp3cz/hDMEs22j+3P5QrJnBrtJz95NBzb5lwNLdkQ7eUZGwfzrgp/9wQa8lEEGpyklcp8b4i2oRbUAA+m2O6CDOZkTNGrnFMZ/qiv5tesqMKkFL0bVI7K8I0XWTnPqUbwqxeGBDEvoAMcyi6XG9QiKHI9jkymKZ1d9R0RDkcDYSo2I1U0g7io/TTuNbnXIB5OE6vLgnbbGzxF2QgKU4YBq4siXSUsDh+UzNb5V9CXnFjE/QTm26GfSH7zjgOyVTxkXtTV1TZCmsgCl99cP3CAAAKTbpGCDLx73rPyLzr/5hjJlCRz2Eh0IARGuARgIRsHLM42t1EOzUytL9yHWahXmkm/rcEgq9Aca8uRoWCgxjb21wYW55X25hbWUSBkdvb2dsZRohCgptb2RlbF9uYW1lEhNBT1NQIG9uIElBIEVtdWxhdG9yGhgKEWFyY2hpdGVjdHVyZV9uYW1lEgN4ODYaHgoLZGV2aWNlX25hbWUSD2dlbmVyaWNfeDg2X2FybRoiCgxwcm9kdWN0X25hbWUSEnNka19ncGhvbmVfeDg2X2FybRpkCgpidWlsZF9pbmZvElZnb29nbGUvc2RrX2dwaG9uZV94ODZfYXJtL2dlbmVyaWNfeDg2X2FybTo5L1BTUjEuMTgwNzIwLjEyMi82NzM2NzQyOnVzZXJkZWJ1Zy9kZXYta2V5cxoeChR3aWRldmluZV9jZG1fdmVyc2lvbhIGMTQuMC4wGiQKH29lbV9jcnlwdG9fc2VjdXJpdHlfcGF0Y2hfbGV2ZWwSATAyDBABKA0wAEAASABQABKJAQqGAQpgEhBQbtEjAwLVppYsdsMzE/4SEhDSjCpqs01inMWMSmcVb8xLEhB58Xip4v073dhXsb9amS5fEhCqPpPd2JJJA+6lSY340bbVEhA+IOisexDKYXINkm5TQahoSOPclZsGEAEaIDE3RENFN0ZFQTQyMTZENUEwMTAwMDAwMDAwMDAwMDAwGAEgj6LvrgYwFTjClPGpARqAAl6QCb4WlcFIDs2h8wRrbzLpmZmUbCFJr2084aEerpyDzp8g34KCDDG+QUG73lSRqpZA6+IyRf5o9NK0U51OiAVcU+XPiAnD2tFFwr+rWJXtTb95ujwGscUZCvKjPEl/OpEnjMMZ3ckGVxSW+YlxBLwF6nftINDou0g26/F2z2mHq674TKZq7Fxh5jBya+zuz1iijl95APrY6uyHabD5xgSZCgXBLCnd4+5SQiH+p7fAciSppMz7p0ZuCSLoswri45ATBtYHWvnZhhKibc89FiGVN+QHbOIEvmHiIuysExhVJgZDhM9z5bKgFOlbQoW4WveumdVyL9HxaduEGxkCGb4=
Raw License Response: b'{"status":2603,"response":["Invalid JSON body"]}'
unable to parse license - check protobufs
Keys => (True, [])
ERROR: [generic] 'f16d7cd6-6227-401f-a0f3-a50a6df21a18.mpd' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:f16d7cd6-6227-401f-a0f3-a50a6df21a18.mpd" ) to search YouTube

**Comment by DevLARLEY** [comment]
are you using mpdl v3.1.0?
i find it weird that the Keys are returning True even though it failed to get the keys and the protobufs error should set that to False
i'll take a look at it in 6 hours

**Comment by mjfarooq** [comment]
Yes I’m using mpdlv3.1.0. Looking forward to your help!

**Comment by DevLARLEY** [comment]
🤦i didn't update pywidevine

**Comment by DevLARLEY** [comment]
did you use the normal or advanced mode?

**Comment by mjfarooq** [comment]
I used the normal mode

**Comment by DevLARLEY** [comment]
stupid mistake, the variable name for the mpd url and mpd file name had teh same name, so they were overwriting themselves. i'll update the code soon.
i'm not sure though why you didn't get any keys

**Comment by DevLARLEY** [comment]
i'll update the code soon, but i have some stuff to do and i also found another mistake, so be patient

**Comment by mjfarooq** [comment]
I think one mistake is at line 1013:
pssh = util.getPSSH(file)     ----->>>  pssh = util.getPSSH(mpd)

I still dont get the keys since the license server seems to expect a json

**Comment by DevLARLEY** [comment]
yes i just fixed that, i didn't see that typo. i'll update the code
[commit](https://github.com/DevLARLEY/mpdl/commit/e1e06a9de461025b6c5f7cf4d9e42da89ac4d679)

**Comment by DevLARLEY** [comment]
it might require a custom format like [here](https://github.com/jiomvk/widevine_keys/blob/main/l3.py)

**Comment by mjfarooq** [comment]
Another mistake for the mpd url overwriting problem. I tried to fix that. Here is the updated part:

 def hanldebutton(self):
        import headers

        i = self.main.sniffer.combobox.currentIndex()
        if i == 0:
            if len(self.listView.selectedItems()) >= 1:
                wid = str(uuid.uuid4())  # worker id
                original_mpd_url = self.listView.selectedItems()[0].text()  

                # get mpd
                writeHeaders(getHeaders(original_mpd_url), original_mpd_url)
                response = requests.get(url=original_mpd_url, headers=headers.headers)
                if not response.ok:
                    errorDialog(self, f"Network error occurred ({response.status_code}) while downloading MPD")
                    return

                temp_mpd_filename = f"{wid}.mpd" 
                with open(temp_mpd_filename, mode="wb") as file:
                    file.write(response.content)
                
                pssh = util.getPSSH(temp_mpd_filename)
                os.remove(temp_mpd_filename)  # Clean up the temporary file

                if pssh is None:
                    errorDialog(self, "No PSSH found in MPD.")
                    return
                else:
                    lic = None
                    for item in [self.listView2.item(x) for x in range(self.listView2.count())]:
                        if item.font().bold():
                            lic = item.text()
                    if lic is None:
                        QMessageBox.information(
                            self,
                            "MPDL/Information",
                            "No License URL selected.",
                            buttons=QMessageBox.Ok,
                            defaultButton=QMessageBox.Ok,
                        )
                        return

                    self.listView.selectedItems()[0].setForeground(Qt.lightGray)

                    pool = QThreadPool.globalInstance()
          
                    worker = Worker(original_mpd_url, pssh, lic, wid)
                    worker.signals.completed.connect(self.main.complete)
                    worker.signals.started.connect(self.main.start)
                    worker.signals.progress.connect(self.main.progress)
                    worker.signals.error.connect(self.main.error)
                    pool.start(worker)
        elif i == 1:
            if len(self.listView2.selectedIndexes()) >= 1:
                font2 = QFont()
                font2.setBold(False)
                for item in [self.listView2.item(x) for x in range(self.listView2.count())]:
                    item.setFont(font2)
                font = QFont()
                font.setBold(True)
                self.listView2.selectedItems()[0].setFont(font)

**Comment by DevLARLEY** [comment]
what did you change?

**Comment by mjfarooq** [comment]
Here are the changes:
- A new variable, original_mpd_url, to store the original MPD URL as obtained from the user's selection. This ensures that the original URL is preserved.
- A new variable, temp_mpd_filename, is created to hold the name of the temporary file (f"{wid}.mpd") that is used for downloading the MPD content and extracting PSSH data. 
- When creating an instance of the Worker class, original_mpd_url is passed as the first argument instead of the temporary file name. 


For the custom format, is there a way to know what format of json does the server expect?

**Comment by DevLARLEY** [comment]
i already fixed these problems [here](https://github.com/DevLARLEY/mpdl/commit/e1e06a9de461025b6c5f7cf4d9e42da89ac4d679) and [here](https://github.com/DevLARLEY/mpdl/commit/c89ed85e7cf82df0fdfc804f0017ce5927d037e7)

for the second part, you might want to contact @medvm on telegram ([here](https://github.com/medvm/widevine_keys)) as i don't do this kind of reverse engineering

**Comment by mjfarooq** [comment]
Cool. I didnt have the latest version perhaps. My problem is only in getting keys due to json. I'll try to figure something out! Thanks so much!!
