### ISSUE TITLE
Choose audio track

### ISSUE THREAD

**Issue by pawelglucklich** [DevLARLEY/mpdl#7]
is there a way to choose which audio track gets picked?

In current vid i try to download there are 2 audio tracks, one is with audio description (which is very annoying) and unfortunately this one is picked as default for vid and audio mix. 

No I cant pick other audio track.

I would love to be able to pick other audio track or have both mixed in, so i could choose from them when playing movie later. Both solutions would work.

**Comment by DevLARLEY** [comment]
You can modify the ytdlp options in the Worker class if you wish to select different audio streams. I won't update this repo anymore, because this program is just a pain to work on. My new program does support this (not sure when i'll release it).

**Comment by pawelglucklich** [comment]
Ok, i resolved it.
For me there was only 2 audio tracks so putting `ba*.2` instead of `ba` was enough to change it to other audio track.

`if not self.d:
                ydl_opts = {
                    'allow_unplayable_formats': True,
                    'noprogress': True,
                    'quiet': True,
                    'fixup': 'never',
                    'format': 'bv,ba*.2',
                    'no_warnings': True,
                    'outtmpl': {'default': self.uuid + '.f%(format_id)s.%(ext)s'},
                    'progress_hooks': [log]
                }`
                
Theres also other option adding `'audio-multistreams': True,` should download all audio tracks, havent tested it but it should work too.
